spring:
  application:
    name: twitter
  datasource:
    url: jdbc:postgresql://localhost:5432/twitter-db
    username: postgres
    password: asdasd123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: create
server:
  port: 3000
#jwt:
#  expiration: 60000000
#  secret: ""

springdoc:
  api-docs:
    path: /api-docs/twitter
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
